### ISSUE TITLE
Difference in period between groundwork and mobility hindrance

### ISSUE THREAD

**Issue by sboden** [Informatievlaanderen/GIPOD#160]
There's a period in both groundwork and mobility hindrance, with one minor difference and I'm wondering whether this intentional or not.

In groundwork the period looks like this:

```
    "period": {
        "@type": "PeriodWithDuration",
        "start": "2020-10-09T11:46:00Z",
        "end": "2021-10-09T19:00:00Z",
        "duration": null
    },
```

While in mobility hindrance it looks like:

```
    "period": [
        {
            "@type": "Period",
            "start": "2020-09-23T12:15:00Z",
            "end": "2020-11-01T09:55:00Z"
        }
    ],
```
Mobility hindrance seems to imply there could be multiple entries in period (an "array of"). I have been looking to mobility hindrances on the beta environment but haven't found a mobility hindrance with more than 1 period. Is this a bug/oversight in mobility hindrance, or what is the condition in which we can get multiple entries in period of mobility hindrance?

**Comment by AIV-Bert** [comment]
Hi @sboden,

A groundwork only has one period by design. As a feature exclusively for groundwork there is an option to define the period of a groundwork by startdate and duration.

An event, work or mobility hindrance can be defined by one or more periods, or by a recurrence.

When can a mobility hindrance have multiple entries? Whenever you like. Users are free to express the timespan of the mobilty hindrance in any way.
 An example: a street needs new boardwalk, this will start today and last 3 months. The mobility hindrance may only be during workdays, so you setup a time-schedule during these 3 months that excludes the weekends. 

Hope this helps.

Kind regards,

Bert
