### ISSUE TITLE
Update period of intake that is in the past

### ISSUE THREAD

**Issue by berdienderoo** [Informatievlaanderen/GIPOD#186]
Is it possible to update the period of a work or event when the period is in the past?
E.g. An intake is registered to take place from 1/10/20-1/11/20. However, This was wrongly registered and should be 1/10/20-6/11/20. Currently, we always receive the error: "Work should be in WorkStatus: Voorontwerp, Niet-concreet gepland, Concreet gepland or In uitvoering". However, we would like to update this to have correct information in GIPOD.

**Comment by AIV-Bert** [comment]
Hi @berdienderoo,

First of all thank you for your motivation to keep the data quality high.

You see this error because the api doesn't allow a public domain occupancy to be changed once it reaches the status 'Uitgevoerd'.

The current workaround is:

- Change the status to Voorontwerp, Niet-concreet gepland, Concreet gepland or In uitvoering and change the period to a valid value for that status
- Change the period to the correct period and set the status back to 'Uigevoerd'

I agree this is not a user friendly experience. I'll update this issue once the team has discussed this.

Kind regards,

Bert

**Comment by AIV-Bert** [comment]
We have prepared a solution, but due to its impact this will first be discussed on an upcoming business workgroup.

**Comment by berdienderoo** [comment]
Thanks for the feedback. Will this be discussed on the business workgroup of tomorrow?
If so, could you let us know the decision or status in this ticket, as we will not be able to join tomorrow.

**Comment by olivermay** [comment]
This was discussed on the business workgroup, the validation rule will be removed.

**Comment by berdienderoo** [comment]
That's great news. Any idea when this will be available in beta?

**Comment by berdienderoo** [comment]
Any update on this? Will this be release before the end of the week as said during the last question hour?

**Comment by olivermay** [comment]
This is now available in beta, see #200 .
