### ISSUE TITLE
Question on Gipod PROD 

### ISSUE THREAD

**Issue by rajeevchugh71** [Informatievlaanderen/GIPOD#201]
Hello,

From Proximus network we are able to get a response from all GET taxonomies APIs (api/v1/taxonomies/) in Gipod PROD. However, we get HTTP 401 when calling for ex. GET on api/v1/groundworks/10211192.

Could you pls advise us what's wrong in the setup at the earliest?

Thanks & br,
Rajeev.

**Comment by SilPal** [comment]
@olivermay , could you please advise ?
Thanks.
Silvie

**Comment by vmateiaiv** [comment]
Dear @rajeevchugh71 ,

We were able to locate your request for GET on api/v1/groundworks/10211192 in our logs and we can see that the reason for the error is because you did  not send an access token in the request header.

It works for the GET taxonomies APIs (api/v1/taxonomies/) because that endpoint is open (no authentication needed).
 But for the GET on api/v1/groundworks/10211192 you need to authenticate with an access token (bearer token).

Please try again with an access token and let us know if it worked.

Kind regards,
Voicu Matei
AIV.

**Comment by rajeevchugh71** [comment]
Thanks a lot @vmateiaiv ! We'll test the setup again today afternoon & feedback.
