### ISSUE TITLE
Discrepancies between ContactOrganisation and ContactOrganisationLd

### ISSUE THREAD

**Issue by ireactsam** [Informatievlaanderen/GIPOD#67]
Hi,

I noticed some differences in optionality, case, naming, or missing fields:

ContactOrganisation | ContactOrganisationLd
---------------------|------------------------
roleId optional but actually required | role.id optional
isPublic optional | contactInformation.isPublic required
email required | contactInformation.email optional
organisationId | -
organisationName | -
contactName (camelCase) | contactInformation.contactname (lowercase)
fax | -
address.streetName | contactInformation.address.streetname
address.houseNumber | contactInformation.address.housenumber
address.boxNumber | contactInformation.address.boxnumber
address.zipCode | contactInformation.address.postalcode
address.cityName | contactInformation.address.municipalityName
address.countryCode | contactInformation.address.country

kr

**Comment by AIV-Bert** [comment]
Hi @ireactsam,

Due to time constrains before release, we could not resolve your issue. Now that the API is in production, these changes are breaking. 

This bug is added to our backlog, but won't be resolved in the near future. We will however adress this when the opportunity arises.

Thank you for pointing out these discrepancies to us.

Kind regards,

Bert
